version: '3.8'

services:
  docker-url-shortener:
    build:
      context: .
    image: url-shortener:latest
    ports:
      - 8080:8080
    environment:
      - SQLITE_DSN=${SQLITE_DSN:-file::memory:?cache=shared}
