version: '3.8'

services:
  docker-url-shortener:
    depends_on:
      - docker-postgres
    build:
      context: ../..
    image: url-shortener:latest
    container_name: url-shorten-golang-rest-server
    networks:
      - url-shorten-network
    ports:
      - 8080:8080

  docker-postgres:
    image: postgres
    container_name: url-shorten-postgre
    hostname: db-postgres
    networks:
      - url-shorten-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  url-shorten-network:
    driver: bridge
