apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: docker-url-shortener
  name: url-shorten-app
  namespace: url-shorten-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: docker-url-shortener
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: docker-url-shortener
    spec:
      containers:
        - image: ghcr.io/siongui/go-kit-url-shortener-micro-service:main
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "YOUR_PASSWORD"
            - name: POSTGRES_HOST
              value: "YOUR_SUBDOMAIN.rds.amazonaws.com"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "YOUR_DATABASE_NAME"
          name: url-shorten-app
          ports:
            - name: tcp
              containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
